import HorizontalSum

/-! `#print axioms` を全宣言に対して流す。`fourfold_lean.py` がこの出力を読む。 -/

#print axioms HorizontalSum.toStd_le_iff
#print axioms HorizontalSum.stdEquiv
#print axioms HorizontalSum.stdEquiv_axis
#print axioms HorizontalSum.axes_join_to_world
#print axioms HorizontalSum.axes_meet_at_lmonad
#print axioms HorizontalSum.same_axis_sup
#print axioms HorizontalSum.same_axis_inf
#print axioms HorizontalSum.ofAxisEquiv
#print axioms HorizontalSum.conj_involutive
#print axioms HorizontalSum.rot_pow_four
#print axioms HorizontalSum.lrot
#print axioms HorizontalSum.rrot
#print axioms HorizontalSum.lrot_rrot_comm
#print axioms HorizontalSum.axes_homogeneous
#print axioms HorizontalSum.no_distinguished_axis
#print axioms HorizontalSum.relative_label_invariant
#print axioms HorizontalSum.relative_label_invariant'
#print axioms HorizontalSum.axes_form_a_torsor
#print axioms HorizontalSum.lrot_comm_of_comm
#print axioms HorizontalSum.q8_card
#print axioms HorizontalSum.q8_not_comm
#print axioms HorizontalSum.lrot_not_comm
#print axioms HorizontalSum.four_lrot_comm
#print axioms HorizontalSum.eight_axes_join_to_world
#print axioms HorizontalSum.eight_axes_meet_at_lmonad
#print axioms HorizontalSum.one4
#print axioms HorizontalSum.aquad
#print axioms HorizontalSum.orderIso_eq_refl_of_wellFounded
#print axioms HorizontalSum.not_wellFounded_of_nontrivial_clock
#print axioms HorizontalSum.axis_infinite_of_nontrivial_clock
#print axioms HorizontalSum.infinite_of_nontrivial_clock
#print axioms HorizontalSum.prod_mid_isCompl_unique
#print axioms HorizontalSum.no_product_decomposition
#print axioms HorizontalSum.chi_lmonad
#print axioms HorizontalSum.chi_world
#print axioms HorizontalSum.chi_lmonad_support
#print axioms HorizontalSum.chi_world_support
#print axioms HorizontalSum.chi_support
#print axioms HorizontalSum.chi_onehot_iff
#print axioms HorizontalSum.chi_allones_iff
#print axioms HorizontalSum.chi_antitone
#print axioms HorizontalSum.chi_le_iff
#print axioms HorizontalSum.chi_world_infinite_support
#print axioms HorizontalSum.Psi_le_iff
#print axioms HorizontalSum.Phi_eq_univ_iff
#print axioms HorizontalSum.Down_eq_univ_iff
#print axioms HorizontalSum.Phi_eq_singleton_iff
#print axioms HorizontalSum.Down_eq_singleton_iff
#print axioms HorizontalSum.univ_isRect
#print axioms HorizontalSum.singleton_isRect
#print axioms HorizontalSum.Phi_bot_isRect
#print axioms HorizontalSum.Phi_top_isRect
#print axioms HorizontalSum.diagonal_not_isRect
#print axioms HorizontalSum.reshape_two
#print axioms HorizontalSum.reshape_rank
#print axioms HorizontalSum.no_reshape_of_finite
#print axioms HorizontalSum.trunc_finite
#print axioms HorizontalSum.trunc_sup_mem
#print axioms HorizontalSum.trunc_inf_mem
#print axioms HorizontalSum.no_clock_inside_trunc
#print axioms HorizontalSum.foldable_of_smul
#print axioms HorizontalSum.smul_of_foldable
#print axioms HorizontalSum.foldable_iff_smul
#print axioms HorizontalSum.foldableMul_of_zpow
#print axioms HorizontalSum.zpow_of_foldableMul
#print axioms HorizontalSum.additive_and_multiplicative_are_dual
#print axioms HorizontalSum.cos_not_foldable
#print axioms HorizontalSum.mixing_needs_arithmetic_steps
#print axioms HorizontalSum.endpoint_perm
#print axioms HorizontalSum.endpoint_zip
#print axioms HorizontalSum.endpoint_not_perm_of_noncomm
#print axioms HorizontalSum.superposition_iff_commutative
#print axioms HorizontalSum.shiftBy_comp
#print axioms HorizontalSum.clock_shiftBy_comp
#print axioms HorizontalSum.clock_iterate_shiftBy
#print axioms HorizontalSum.mixing_identity
#print axioms HorizontalSum.addition_is_inside_the_axis
#print axioms HorizontalSum.trunc_approximates
#print axioms HorizontalSum.trunc_clock_step
#print axioms HorizontalSum.trunc_union
#print axioms HorizontalSum.clock_sup
#print axioms HorizontalSum.Phi_act
#print axioms HorizontalSum.Phi_act_twice
#print axioms HorizontalSum.act_comp_is_affine
#print axioms HorizontalSum.trunc_mono
#print axioms HorizontalSum.clockPow_sup
#print axioms HorizontalSum.clockPow_add
#print axioms HorizontalSum.Semi.mul_left_of_trivial
#print axioms HorizontalSum.Semi.is_direct_product_when_trivial
#print axioms HorizontalSum.Semi.inl_mul
#print axioms HorizontalSum.Semi.inr_mul
#print axioms HorizontalSum.Semi.inl_mul_inr
#print axioms HorizontalSum.Semi.coe_eq_inl_mul_inr
#print axioms HorizontalSum.Semi.inr_inl_comm
#print axioms HorizontalSum.act_eq_smul
#print axioms HorizontalSum.act_eq_mul_left
#print axioms HorizontalSum.mul_right_counts
#print axioms HorizontalSum.mul_three
#print axioms HorizontalSum.trunc_act_step
#print axioms HorizontalSum.trunc_act_approximates
#print axioms HorizontalSum.shift_one4
#print axioms HorizontalSum.aquad_eq
#print axioms HorizontalSum.aquad_zero
#print axioms HorizontalSum.aquad_sum
#print axioms HorizontalSum.shift_aquad
#print axioms HorizontalSum.shift_shift_aquad
#print axioms HorizontalSum.aquad_quadratic
#print axioms HorizontalSum.aquad_pos
#print axioms HorizontalSum.aquad_prob
#print axioms HorizontalSum.one4_uniform
#print axioms HorizontalSum.lrot_comm_of_mem_center
#print axioms HorizontalSum.sum_translate_invariant
#print axioms HorizontalSum.q8_center_nontrivial
#print axioms HorizontalSum.q8_center_proper
#print axioms HorizontalSum.one4_eq_sum_basis
#print axioms HorizontalSum.basis_not_invariant
#print axioms HorizontalSum.basis_sum_not_invariant
#print axioms HorizontalSum.reaches_exactly_one_axis
#print axioms HorizontalSum.two_kinds_of_non_lmonad
#print axioms HorizontalSum.harm_self_or_other
#print axioms HorizontalSum.harm_nothing
#print axioms HorizontalSum.cmat
#print axioms HorizontalSum.qmat
#print axioms HorizontalSum.qmat_one
#print axioms HorizontalSum.qmat_scalar
#print axioms HorizontalSum.qmat_mul
#print axioms HorizontalSum.qmat_conj
#print axioms HorizontalSum.cmat_conj
#print axioms HorizontalSum.cmat_det
#print axioms HorizontalSum.qmat_trace
#print axioms HorizontalSum.qmat_injective
#print axioms HorizontalSum.qmat_not_comm
#print axioms HorizontalSum.cmat_comm
#print axioms HorizontalSum.zmod_four_ne
#print axioms HorizontalSum.rot_axis
#print axioms HorizontalSum.rot_bot
#print axioms HorizontalSum.rot_top
#print axioms HorizontalSum.rot_ne_self
#print axioms HorizontalSum.quad_join_to_world
#print axioms HorizontalSum.quad_meet_at_lmonad
#print axioms HorizontalSum.rot_join_meet
#print axioms HorizontalSum.pathAmp
#print axioms HorizontalSum.amp_perm_invariant
#print axioms HorizontalSum.visited
#print axioms HorizontalSum.visited_length
#print axioms HorizontalSum.amp_perm_not_invariant
#print axioms HorizontalSum.quad
#print axioms HorizontalSum.shift
#print axioms HorizontalSum.quad_sum
#print axioms HorizontalSum.shift_quad
#print axioms HorizontalSum.shift_shift_quad
#print axioms HorizontalSum.shift_four
#print axioms HorizontalSum.quad_zero
#print axioms HorizontalSum.smul_quad
#print axioms HorizontalSum.all_phases_one_world
#print axioms HorizontalSum.all_phases_meet_at_lmonad
#print axioms HorizontalSum.four_phases_one_world
#print axioms HorizontalSum.four_phases_meet_at_lmonad
#print axioms HorizontalSum.quarter
#print axioms HorizontalSum.clock_mono
#print axioms HorizontalSum.clock_injective
#print axioms HorizontalSum.seven
#print axioms HorizontalSum.eight
#print axioms HorizontalSum.six
#print axioms HorizontalSum.five
#print axioms HorizontalSum.four
#print axioms HorizontalSum.nine
#print axioms HorizontalSum.clock_axioms
#print axioms HorizontalSum.clockIso
#print axioms HorizontalSum.infinite_of_infinite
#print axioms HorizontalSum.form
#print axioms HorizontalSum.sigma_fixes_lmonad
#print axioms HorizontalSum.factors_through_lmonad
#print axioms HorizontalSum.second_stage_ignores_target
#print axioms HorizontalSum.second_stage_forgets
#print axioms HorizontalSum.actor_from_lmonad
#print axioms HorizontalSum.target_from_lmonad
#print axioms HorizontalSum.order_is_lmonad
#print axioms HorizontalSum.lmonad_takes_form
#print axioms HorizontalSum.clock_symm_clock
#print axioms HorizontalSum.sigma_surjective
#print axioms HorizontalSum.only_lmonad_is_traceable
#print axioms HorizontalSum.lmonad_acts_by_the_clock
#print axioms HorizontalSum.same_axis_act
#print axioms HorizontalSum.cross_axis_act
#print axioms HorizontalSum.confinement
#print axioms HorizontalSum.image_of_act
#print axioms HorizontalSum.lmonad_reaches_everything
#print axioms HorizontalSum.bot_isCompl_unique
#print axioms HorizontalSum.top_isCompl_unique
#print axioms HorizontalSum.complement_not_unique
#print axioms HorizontalSum.bact
#print axioms HorizontalSum.branch_seven
#print axioms HorizontalSum.branch_six
#print axioms HorizontalSum.branch_eight
#print axioms HorizontalSum.branch_four
#print axioms HorizontalSum.branch_five
#print axioms HorizontalSum.branch_actor
#print axioms HorizontalSum.cone_filled
#print axioms HorizontalSum.cone_single
#print axioms HorizontalSum.trace
#print axioms HorizontalSum.world_absorbing_target
#print axioms HorizontalSum.world_absorbing_actor
#print axioms HorizontalSum.trace_mono
#print axioms HorizontalSum.all_lmonad_stays
#print axioms HorizontalSum.same_axis_never_world
#print axioms HorizontalSum.trace_stays_on_axis
#print axioms HorizontalSum.lmonad_can_become_anything
#print axioms HorizontalSum.only_lmonad_can_become_anything
#print axioms HorizontalSum.Phi
#print axioms HorizontalSum.Phi_bot
#print axioms HorizontalSum.Phi_sup
#print axioms HorizontalSum.Phi_antitone
#print axioms HorizontalSum.Phi_injective
#print axioms HorizontalSum.Phi_cross_axis
#print axioms HorizontalSum.Phi_inf_superset
#print axioms HorizontalSum.Phi_inf_ne
#print axioms HorizontalSum.Phi_clock
#print axioms HorizontalSum.Phi_eq_Ici
#print axioms HorizontalSum.Down
#print axioms HorizontalSum.Down_top
#print axioms HorizontalSum.Down_bot
#print axioms HorizontalSum.Down_inf
#print axioms HorizontalSum.Down_monotone
#print axioms HorizontalSum.Down_injective
#print axioms HorizontalSum.two_directions
#print axioms HorizontalSum.lmonad_world_mirror
#print axioms HorizontalSum.Psi
#print axioms HorizontalSum.Psi_bot
#print axioms HorizontalSum.Psi_top
#print axioms HorizontalSum.Psi_sup
#print axioms HorizontalSum.Psi_antitone
#print axioms HorizontalSum.Psi_axis_self
#print axioms HorizontalSum.Psi_axis_other
#print axioms HorizontalSum.star_shape
#print axioms HorizontalSum.clockPow_eq_iterate
#print axioms HorizontalSum.chi_eq_indicator
#print axioms HorizontalSum.pathAmp_eq_map_prod
#print axioms HorizontalSum.endpoint_eq_prod_mul
#print axioms HorizontalSum.trunc_axis_mem
#print axioms HorizontalSum.Phi_Down_are_intervals
#print axioms HorizontalSum.isRect_iff_prod
#print axioms HorizontalSum.shift_are_addRight
#print axioms HorizontalSum.lrot_rrot_are_translations
#print axioms HorizontalSum.qmat_mul_regular
#print axioms HorizontalSum.cmat_mul
#print axioms HorizontalSum.quad_shift_is_cyclic
#print axioms HorizontalSum.shift_pow_four
#print axioms HorizontalSum.ofAxisEquiv_is_relabel
#print axioms HorizontalSum.clock_is_componentwise
#print axioms HorizontalSum.clock_relabel_not_comm
#print axioms HorizontalSum.Family.mid_incomparable
#print axioms HorizontalSum.Family.mid_le_iff
#print axioms HorizontalSum.Family.le_mid_iff
#print axioms HorizontalSum.Family.mid_isLUB_iff
#print axioms HorizontalSum.Family.cross_isLUB
#print axioms HorizontalSum.Family.cross_isGLB
#print axioms HorizontalSum.Family.two_not_lattice
#print axioms HorizontalSum.Family.two_hsum_has_lub
#print axioms HorizontalSum.Family.eEquiv
#print axioms HorizontalSum.Family.eEquiv_sup
#print axioms HorizontalSum.Family.eEquiv_inf
#print axioms HorizontalSum.Family.sup_cross
#print axioms HorizontalSum.Family.inf_cross
#print axioms HorizontalSum.Family.sup_inside
#print axioms HorizontalSum.Family.inf_inside
#print axioms HorizontalSum.not_distributive
#print axioms HorizontalSum.not_modular
#print axioms HorizontalSum.Family.mid_ne_bot
#print axioms HorizontalSum.Family.mid_ne_top
#print axioms HorizontalSum.Family.mid_isHorizontalSum
#print axioms HorizontalSum.IsHorizontalSum.injective
#print axioms HorizontalSum.IsHorizontalSum.ne_of_ne_index
#print axioms HorizontalSum.IsHorizontalSum.emb_eq_transport
#print axioms HorizontalSum.IsHorizontalSum.transfer_bot
#print axioms HorizontalSum.IsHorizontalSum.transfer_top
#print axioms HorizontalSum.IsHorizontalSum.transfer_mid
#print axioms HorizontalSum.IsHorizontalSum.same_component_of_comparable
#print axioms HorizontalSum.IsHorizontalSum.not_le_bot
#print axioms HorizontalSum.IsHorizontalSum.not_top_le
#print axioms HorizontalSum.IsHorizontalSum.cross_sup_top
#print axioms HorizontalSum.IsHorizontalSum.cross_inf_bot
#print axioms HorizontalSum.clockPow_id
#print axioms HorizontalSum.semi_comm_iff
#print axioms HorizontalSum.semi_not_comm_of_clock_ne
#print axioms HorizontalSum.SupM.out_of
#print axioms HorizontalSum.SupM.of_out
#print axioms HorizontalSum.SupM.mul_def
#print axioms HorizontalSum.SupM.one_def
#print axioms HorizontalSum.MSemi.ext'
#print axioms HorizontalSum.MSemi.mul_left
#print axioms HorizontalSum.MSemi.mul_right
#print axioms HorizontalSum.MSemi.one_left
#print axioms HorizontalSum.MSemi.one_right
#print axioms HorizontalSum.MSemi.inl_mul
#print axioms HorizontalSum.MSemi.inr_mul
#print axioms HorizontalSum.MSemi.inl_mul_inr
#print axioms HorizontalSum.MSemi.factor
#print axioms HorizontalSum.MSemi.inr_inl_comm
#print axioms HorizontalSum.MSemi.mul_of_trivial
#print axioms HorizontalSum.clockEnd
#print axioms HorizontalSum.semiMulEquiv
