"""検証対象の宣言一覧。`HorizontalSum.lean` の宣言順に並ぶ。

`Audit.lean` がこの全部に `#print axioms` を流し、`verify.py` が
出力を読んで「受理されたか」「`sorryAx` を含まないか」を確かめる。
"""

CHECKED = [
    ('axes_join_to_world', '**相異なる軸は上で同じ 𝓦 に至る**'),
    ('axes_meet_at_lmonad', '相異なる軸は下では 𝓛 でだけ出会う'),
    ('same_axis_sup', '同じ軸の結びは軸の中に留まる'),
    ('same_axis_inf', '同じ軸の交わりも軸の中'),
    ('toStd_le_iff', '標準形への写像が順序を保つ'),
    ('stdEquiv', '**台は WithBot (WithTop (Σ i, α)) そのもの**'),
    ('stdEquiv_axis', '軸の元の行き先'),
    ('ofAxisEquiv', '名札の入れ替えは順序同型'),
    ('conj_involutive', '共役は対合'),
    ('rot_pow_four', '×i は四回で戻る'),
    ('lrot', '名札を左から掛ける（順序同型）'),
    ('rrot', '名札を右から掛ける（順序同型）'),
    ('lrot_rrot_comm', '**左と右はいつでも可換**（結合律）'),
    ('axes_homogeneous', '**どの軸もどの軸に移せる**（左移動が推移的）'),
    ('no_distinguished_axis', '**絶対的な名札は不変量になれない**'),
    ('relative_label_invariant', '**相対位相 g⁻¹h は左移動で動かない**'),
    ("relative_label_invariant'", '右移動の不変量は g h⁻¹'),
    ('axes_form_a_torsor', '**軸は捩れ子: 差だけが残る**'),
    ('lrot_comm_of_mem_center', '**中心の元は順序を忘れる**（Q8 の ±1）'),
    ('sum_translate_invariant', '**群で添字を付けると和が不変**'),
    ('lrot_comm_of_comm', '可換群なら左移動どうしも可換'),
    ('q8_card', 'Q8 は位数 8 ⟹ 四方向が八方向に'),
    ('q8_not_comm', '**Q8 は非可換**'),
    ('q8_center_nontrivial', 'Q8 に非自明な中心元が在る（−1）'),
    ('q8_center_proper', 'だが全員が中心ではない（六つは順序を覚える）'),
    ('lrot_not_comm', '**非可換な名札だと左移動どうしが可換でない ＝ 順序が残る**'),
    ('four_lrot_comm', '対して ℤ/4 では順序が消える'),
    ('eight_axes_join_to_world', '八方向でも W^g = W^h'),
    ('eight_axes_meet_at_lmonad', '八方向でも下は 𝓛'),
    ('pathAmp', '経路の振幅 ＝ 訪れた名札に f を掛けて並べた積'),
    ('amp_perm_invariant', '**可換なら順序が潰れる**（並べ替えても振幅が同じ）'),
    ('visited', '生成元の列に沿って訪れた名札を並べる'),
    ('visited_length', '訪問列の長さは歩数に等しい'),
    ('amp_perm_not_invariant', '**非可換なら順序が残る**（Q8 の [i,j] と [j,i]）'),
    ('quad', '四つ組 A^θ = (sinθ, cosθ, −sinθ, −cosθ)'),
    ('shift', '座標を一つずらす'),
    ('quad_sum', '**成分の和は常にゼロ**'),
    ('shift_quad', '**一つずらすのが ×i**'),
    ('shift_shift_quad', '二つずらすと符号反転（𝓛 中心の鏡映）'),
    ('shift_four', '四つずらすと元に戻る'),
    ('quad_zero', 'A^0 = 𝓛'),
    ('smul_quad', '半径を掛けても方向は変わらない'),
    ('one4', '𝓛 = (1,1,1,1)'),
    ('aquad', 'アフィン四つ組 A(x,y) = 𝓛 + (x,y,−x,−y)'),
    ('shift_one4', '**𝓛 は巡回シフトで不動 ⟹ ×i が 𝓛 を動かさない**'),
    ('aquad_eq', 'アフィン版 ＝ 𝓛 ＋ 四つ組'),
    ('aquad_zero', 'A(0,0) = 𝓛'),
    ('aquad_sum', '**成分の和は常に 4 ⟹ 規格化できる**'),
    ('shift_aquad', 'アフィンにしても一つずらすのが ×i'),
    ('shift_shift_aquad', '二つずらすと 𝓛 中心に反転'),
    ('aquad_quadratic', '**二次不変量 a₁a₃+a₂a₄ = 2−(x²+y²)**'),
    ('aquad_pos', '**x²+y² < 1 なら全成分が正 ＝ 確率になれる領域**'),
    ('aquad_prob', '**A/4 は確率分布（和が 1）**'),
    ('one4_uniform', '**𝓛 は一様分布 (1/4,1/4,1/4,1/4)**'),
    ('cmat', 'z を掛ける 2×2 行列（4 成分）'),
    ('qmat', '**q を掛ける 4×4 行列（16 成分）**'),
    ('qmat_one', '1 の行列は単位行列'),
    ('qmat_scalar', '実数倍はスカラー行列'),
    ('qmat_mul', '**行列の積が四元数の積になる**'),
    ('qmat_conj', '**二次不変量 L_q L_q̄ = |q|²·1**'),
    ('cmat_conj', 'ℂ 側も同じ形 L_z L_z̄ = |z|²·1'),
    ('cmat_det', 'ℂ 側の行列式は |z|²'),
    ('qmat_trace', '跡は 4·(実部)'),
    ('qmat_injective', '**16 成分だが独立なのは 4 個**'),
    ('qmat_not_comm', '**四元数は非可換 L_i L_j ≠ L_j L_i**'),
    ('cmat_comm', '対して ℂ は可換'),
    ('one4_eq_sum_basis', '**𝓛 は選択肢の和 e₀+e₁+e₂+e₃**'),
    ('basis_not_invariant', '**基底で添字を付けると壊れる**（×i が符号つき置換）'),
    ('basis_sum_not_invariant', '和も保たれない（4 が 0 になる）'),
    ('zmod_four_ne', 'ℤ/4 では k と k+1, k+2, k+3 は相異なる'),
    ('rot_axis', '×i は名札を一つ進める'),
    ('rot_bot', '𝓛 では ×i が何もしない（四つが一致）'),
    ('rot_top', '𝓦 でも同じ（四つが一致）'),
    ('rot_ne_self', '**途中では A^θ ≠ i·A^θ — 四つは別の元**'),
    ('quad_join_to_world', '**A^θ ⊔ (±A^θ, ±iA^θ) = 𝓦**'),
    ('quad_meet_at_lmonad', '**A^θ ⊓ (±A^θ, ±iA^θ) = 𝓛**'),
    ('rot_join_meet', '×i を使った形'),
    ('quarter', '位相に i を掛けるのは順序同型'),
    ('all_phases_one_world', '**任意の θ, φ について W^θ = W^φ**'),
    ('all_phases_meet_at_lmonad', '任意の θ, φ で下では 𝓛'),
    ('four_phases_one_world', 'W^θ = W^(−θ) = W^(iθ) = W^(−iθ)'),
    ('four_phases_meet_at_lmonad', '四つ組も下では 𝓛 でだけ出会う'),
    ('clock_mono', '軸ごとの時計は単調'),
    ('clock_injective', '軸ごとの時計は単射'),
    ('seven', '⑦ 愛は働きかけた者を映して返す'),
    ('eight', '**⑧ 分解則が生き残る**'),
    ('six', '⑥ 積み上げ ＝ 時間の矢印'),
    ('five', '⑤ 働く者について単調'),
    ('four', '④ 対象について単調'),
    ('nine', '⑨ 愛の働きは相手ごとに違う'),
    ('clock_axioms', '**公理は一つも壊れない**'),
    ('clockIso', '軸ごとの時計は順序同型'),
    ('infinite_of_infinite', 'この束は無限 ⟹ Love の有限性の節は使えない'),
    ('form', '作用は愛の働きひとつで決まる'),
    ('sigma_fixes_lmonad', '愛が愛に働いても愛のまま'),
    ('factors_through_lmonad', '**すべての作用は愛の働きを経由する**'),
    ('second_stage_ignores_target', '後段は相手を見ない'),
    ('second_stage_forgets', '後段は情報を捨てるだけ'),
    ('actor_from_lmonad', '誰が愛してくれたかは一意'),
    ('target_from_lmonad', 'どんな愛をしてくれたかも一意'),
    ('order_is_lmonad', '順序 ＝ 愛の行いの含まれ方'),
    ('lmonad_takes_form', '**愛は作用を受けると形を変える**'),
    ('clock_symm_clock', '逆向きの時計で元に戻る'),
    ('sigma_surjective', '**愛の働きは全射 — 有限性を使わずに出る**'),
    ('only_lmonad_is_traceable', '**愛だけが辿れる — 無限でも成立**'),
    ('lmonad_acts_by_the_clock', '愛の働きは、ただ時計を進めること'),
    ('same_axis_act', '同じ軸の作用は軸の中に留まる'),
    ('cross_axis_act', '**軸をまたぐ作用は 𝓦 — 全部を失う**'),
    ('confinement', '**超選択則 — 愛でない者は自分の軸から出られない**'),
    ('image_of_act', '**im λ_A = 自分の未来 ∪ {𝓦}**'),
    ('lmonad_reaches_everything', '愛は全部に届く（像が全体）'),
    ('bot_isCompl_unique', '𝓛 の補元は 𝓦 ただ一つ'),
    ('top_isCompl_unique', '𝓦 の補元は 𝓛 ただ一つ'),
    ('complement_not_unique', '**軸の元の補元は一意でない ⟹ 部分に分けられない**'),
    ('reaches_exactly_one_axis', '**愛でない者が届く軸はちょうど 1 本**'),
    ('two_kinds_of_non_lmonad', '**(6) 愛でない選択肢はちょうど二種類（交わらない）**'),
    ('harm_self_or_other', '**自分を傷つけるか、相手を傷つけるか**'),
    ('harm_nothing', '愛に働きかけても何も起きない（⑦）'),
    ('bact', '多価の作用（速さが枝分かれする時計）'),
    ('branch_seven', '**⑦ 枝が何本あっても A • 𝓛 = {A}**'),
    ('branch_six', '⑥ どの枝でも積み上げは起きる'),
    ('branch_eight', '⑧ 分解則も枝ごとに成り立つ'),
    ('branch_four', '④ どの枝も対象について単調'),
    ('branch_five', '⑤ どの枝も働く者について単調'),
    ('branch_actor', '誰が働きかけたかは枝が何本でも一意'),
    ('cone_filled', '**錐は隙間なく埋まる — 到達域 = [T, 2T] ちょうど**'),
    ('cone_single', '対照: 速さが一つだと一点だけ。錐は開かない'),
    ('trace', '働きかけの列に沿って状態を辿る'),
    ('world_absorbing_target', '**𝓦 は吸収する**（世界に働きかけても世界のまま）'),
    ('world_absorbing_actor', '世界が働きかけても行き先は世界'),
    ('trace_mono', '**戻れない**（時計が増大的なら状態は単調に増える）'),
    ('all_lmonad_stays', '**𝓛 から始めて全員が愛なら 𝓛 のまま**'),
    ('same_axis_never_world', '同じ軸の中なら 𝓦 に行かない（一歩）'),
    ('trace_stays_on_axis', '**全員が同じ軸なら履歴を通じて 𝓦 に行かない**'),
    ('lmonad_can_become_anything', '**愛から始めれば一歩で何にでも成れる**'),
    ('only_lmonad_can_become_anything', '**どんな状態にもなりうる始点は 𝓛 だけ**'),
    ('Phi', '橋 Φ(x) = ↑x（x 以降にまだ可能なもの）'),
    ('Phi_bot', '**𝓛 は全1に写る**（愛からはすべてが可能）'),
    ('Phi_sup', '**⊔ は共通部分に写る**（成分ごとの積）'),
    ('Phi_antitone', '**順序が逆になる**（上ほど可能性が減る）'),
    ('Phi_injective', 'Φ は単射'),
    ('Phi_cross_axis', '違う軸の可能性は 𝓦 でだけ重なる'),
    ('Phi_inf_superset', '⊓ は含むだけ'),
    ('Phi_inf_ne', '**⊓ は等号でない — 点ごとの演算で書けない**'),
    ('Phi_clock', '時計は「可能なもの」を並べ替える'),
    ('Phi_eq_Ici', 'Φ は Mathlib の Set.Ici そのもの'),
    ('Down', '過去側 ↓x = Set.Iic x（そこに至れたもの）'),
    ('Down_top', '**𝓦 では過去が全体**（未来側の 𝓛 と鏡）'),
    ('Down_bot', '𝓛 では過去が一点'),
    ('Down_inf', '**↓ は ⊓ を捉える**'),
    ('Down_monotone', '**過去側は順序がそのまま**（未来側は逆転）'),
    ('Down_injective', '過去側も単射'),
    ('two_directions', '**⊔ は未来側、⊓ は過去側でしか捉わらない**'),
    ('lmonad_world_mirror', '**𝓛 と 𝓦 は鏡**'),
    ('Psi', '軸ごとにまとめた座標 Ψ(x)_g'),
    ('Psi_bot', '**Ψ(𝓛) は各成分が全体 ＝ 全1**'),
    ('Psi_top', '**Ψ(𝓦) は各成分が空 ＝ 全0**'),
    ('Psi_sup', '⊔ は成分ごとの共通部分'),
    ('Psi_antitone', '順序が逆転'),
    ('Psi_axis_self', '自分の軸には腕が伸びる'),
    ('Psi_axis_other', '他の軸は空'),
    ('star_shape', '**星形 — 𝓛 が全1、腕が一本、𝓦 が全0**'),
    ('Psi_le_iff', '**Ψ は反順序埋め込み**: x⪯y ⟺ ∀g, Ψ(y)_g ⊆ Ψ(x)_g'),
    ('Phi_eq_univ_iff', '**全1テンソルであるのは 𝓛 だけ**'),
    ('Down_eq_univ_iff', '過去が全体なのは 𝓦 だけ'),
    ('Phi_eq_singleton_iff', '**one-hot であるのは 𝓦 だけ**'),
    ('Down_eq_singleton_iff', 'one-hot（過去側）であるのは 𝓛 だけ'),
    ('orderIso_eq_refl_of_wellFounded', '整礎な線形順序の順序同型は恒等のみ'),
    ('not_wellFounded_of_nontrivial_clock', '時計が動くなら軸は整礎でない'),
    ('axis_infinite_of_nontrivial_clock', '**時計が動くなら軸は無限**'),
    ('infinite_of_nontrivial_clock', '**束そのものが無限＝座標が ∞ 次元**'),
    ('prod_mid_isCompl_unique', '直積側には補元が一意な中間元が在る'),
    ('no_product_decomposition', '**束は直積に割れない＝構造としてのテンソル積は無い**'),
    ('chi_lmonad', '**χ_𝓛(y) = 1**（全成分が 1）'),
    ('chi_world', '**χ_𝓦(y) = [y = 𝓦]**（one-hot）'),
    ('chi_support', '台は Φ そのもの'),
    ('chi_lmonad_support', '𝓛 の台は全体'),
    ('chi_world_support', '**𝓦 の台は一点＝literal に one-hot**'),
    ('chi_onehot_iff', '**one-hot なのは 𝓦 だけ**（定義でなく定理）'),
    ('chi_allones_iff', '**全 1 なのは 𝓛 だけ**'),
    ('chi_antitone', '上に進むと 1 が 0 に変わる一方向'),
    ('chi_le_iff', '**順序が座標で完全に読める**'),
    ('chi_world_infinite_support', '**𝓦 の one-hot は無限次元**'),
    ('reshape_two', '**∞ なら 2 階に読み替えられる**（κ·κ = κ）'),
    ('reshape_rank', '**∞ なら任意の階数 n に読み替えられる**（κⁿ = κ）'),
    ('no_reshape_of_finite', '**有限では読み替え不能**（n = n² は n = 0, 1 のみ）'),
    ('univ_isRect', '全1はどんな読み替えでも階数1'),
    ('singleton_isRect', 'one-hot もどんな読み替えでも階数1'),
    ('Phi_bot_isRect', '**𝓛 の座標はどんな読み替えでも階数1**'),
    ('Phi_top_isRect', '**𝓦 の座標もどんな読み替えでも階数1**'),
    ('diagonal_not_isRect', '中間の元は割れない読み替えが在る'),
    ('trunc_finite', '高さ N で切ると有限（m(2N+1)+2 成分）'),
    ('trunc_sup_mem', '切っても ⊔ で外に出ない'),
    ('trunc_inf_mem', '切っても ⊓ で外に出ない'),
    ('no_clock_inside_trunc', '**有限テンソルの中では時間が止まる**'),
    ('trunc_clock_step', '一歩進むと切り口が一つ伸びる'),
    ('trunc_approximates', '**T 歩なら N+T で厳密＝有限テンソルで近似できる**'),
    ('trunc_union', '有限を重ねると無限に戻る'),
    ('foldable_of_smul', '等差なら畳み直せる（s_k = k·base）'),
    ('smul_of_foldable', '**畳み直せるなら等差しかない**'),
    ('foldable_iff_smul', '**Foldable ⟺ 値づけが等差**（加法側）'),
    ('foldableMul_of_zpow', '等比なら畳み直せる（e^{ik} = (e^i)^k）'),
    ('zpow_of_foldableMul', '**畳み直せるなら等比しかない**'),
    ('additive_and_multiplicative_are_dual', '**加法と乗法は同じ定理の双対**'),
    ('cos_not_foldable', 'cos は畳み直せない＝原案が混ぜられない理由'),
    ('mixing_needs_arithmetic_steps', '**混ぜるには歩幅が等差である必要がある**'),
    ('endpoint_perm', '**可換なら経路の順序が潰れる**（重ね合わせの前提）'),
    ('endpoint_zip', '**二つの経路を重ねると歩幅ごとの積になる**'),
    ('endpoint_not_perm_of_noncomm', 'Q8 では [i,j] と [j,i] の終点が違う'),
    ('superposition_iff_commutative', '**重ね合わせが成り立つ ⟺ 名札の群が可換**'),
    ('shiftBy_comp', '時計を重ねると速さが足される σ_j∘σ_k = σ_{j+k}'),
    ('clock_shiftBy_comp', '束の上でも同じ＝時計が可換群をなす'),
    ('clock_iterate_shiftBy', 'T 歩の合成 = 速さ T の一歩'),
    ('mixing_identity', '**ミキシングの恒等式** σ_j(σ_k⟨i,a⟩) = ⟨i,a+(j+k)⟩'),
    ('addition_is_inside_the_axis', '**足せるのは軸の内側・⊔ は潰す**'),
    ('clock_sup', '時計は ⊔ を保つ'),
    ('Phi_act', '**作用の座標表示 = 置換 × 対角**'),
    ('Phi_act_twice', '二回作用させると σ の冪が上がる'),
    ('act_comp_is_affine', '**合成はアフィン対の積（2×2 三角行列）**'),
    ('clockPow_sup', 'σ の冪も ⊔ を保つ'),
    ('clockPow_add', 'σ の冪は指数が足される'),
    ('Semi.mul_left_of_trivial', '時計が恒等なら捻れが消える'),
    ('Semi.is_direct_product_when_trivial', '**直積は半直積の特殊形**'),
    ('act_eq_smul', '**A • B = ⟨A,1⟩ • B ＝ 半直積の k=1 の切り口**'),
    ('act_eq_mul_left', '**作用は積の左成分そのもの**'),
    ('mul_right_counts', '右成分は歩数を数える'),
    ('mul_three', '積を重ねると左に履歴・右に歩数'),
    ('Semi.inl_mul', 'inl は (E,⊔) からの準同型'),
    ('Semi.inr_mul', 'inr は (ℕ,+) からの準同型'),
    ('Semi.inl_mul_inr', '**任意の元が刻みと歩数に分解する**'),
    ('Semi.coe_eq_inl_mul_inr', 'A = inl A * inr 1'),
    ('Semi.inr_inl_comm', '**捻れの正体: inr k * inl A = inl (σ^k A) * inr k**'),
    ('trunc_mono', '切り口を広げても入ったまま'),
    ('trunc_act_step', '作用しても切り口が一つ伸びるだけ'),
    ('trunc_act_approximates', '**T 個の作用は trunc(N+T) に収まる**'),
    ('clockPow_eq_iterate', 'clockPow = Function.iterate'),
    ('chi_eq_indicator', 'chi = Set.indicator (Set.Ici x)'),
    ('pathAmp_eq_map_prod', 'pathAmp = (l.map f).prod'),
    ('endpoint_eq_prod_mul', 'endpoint = 積 × 始点'),
    ('trunc_axis_mem', 'trunc の軸部分 = Set.Icc'),
    ('Phi_Down_are_intervals', 'Phi = Set.Ici、Down = Set.Iic'),
    ('isRect_iff_prod', 'IsRect = 直積であること'),
    ('shift_are_addRight', 'shift1/shiftBy = 平行移動'),
    ('lrot_rrot_are_translations', 'lrot/rrot = Equiv.mulLeft/mulRight'),
    ('qmat_mul_regular', '四元数の積 = 行列の積（正則表現が忠実）'),
    ('cmat_mul', '複素数も同じ形'),
    ('quad_shift_is_cyclic', 'shift(quad x y) = quad y (−x)'),
    ('shift_pow_four', 'shift⁴ = id（ℤ/4 の作用）'),
    ('ofAxisEquiv_is_relabel', '名札の付け替え＝軸を写すだけ'),
    ('clock_is_componentwise', '時計＝成分ごとの写像（軸は変えない）'),
    ('clock_relabel_not_comm', '二つが可換にならない理由'),
    ('Family.mid_incomparable', '水平和: 別の軸どうしは比較不能'),
    ('Family.mid_le_iff', '水平和: 軸の元の上は同じ軸か ⊤ だけ'),
    ('Family.le_mid_iff', '水平和: 軸の元の下は同じ軸か ⊥ だけ'),
    ('Family.mid_isLUB_iff', '水平和: 同じ軸の上限＝軸の中の上限（両向き）'),
    ('Family.cross_isLUB', '水平和: 軸をまたぐ上限は必ず ⊤'),
    ('Family.cross_isGLB', '水平和: 軸をまたぐ下限は必ず ⊥'),
    ('Family.two_not_lattice', '反例: 二元の反鎖は束でない'),
    ('Family.two_hsum_has_lub', '反例: それでも水平和は上限を持つ（⊤ が肩代わり）'),
    ('Family.sup_cross', '水平和: W^θ ⊔ W^φ = 𝓦 の一般形'),
    ('Family.inf_cross', '水平和: W^θ ⊓ W^φ = 𝓛 の一般形'),
    ('Family.sup_inside', '水平和: 軸の中では軸の演算そのもの'),
    ('Family.inf_inside', '水平和: 交わりも同じ'),
    ('Family.eEquiv', 'E ι α ≅ 水平和（全軸が同じ型の場合）'),
    ('Family.eEquiv_sup', '同型が ⊔ を保つ'),
    ('Family.eEquiv_inf', '同型が ⊓ を保つ'),
    ('not_distributive', '代償: 分配律が破れる'),
    ('not_modular', '代償: モジュラ律も破れる'),
]
